apiVersion: apps/v1
kind: Deployment
metadata:
  name: prospectus-backend-scrape
spec:
  replicas: 4
  selector:
    matchLabels:
      app: prospectus-backend-scrape
  template:
    metadata:
      labels:
        app: prospectus-backend-scrape
    spec:
      containers:
      - name: prospectus-backend-scrape
        image: warpwing/hoyastest:latest
        ports:
        - containerPort: 6000
