apiVersion: v1
kind: Service
metadata:
  name: prospectus-backend-scrape-svc
spec:
  selector:
    app.kubernetes.io/name: prospectus-backend-scrape-svc
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000