apiVersion: apps/v1
kind: Deployment
metadata:
  name: prospectus-backend-retrieve
spec:
  replicas: 4
  selector:
    matchLabels:
      app: prospectus-backend-retrieve
  template:
    metadata:
      labels:
        app: prospectus-backend-retrieve
    spec:
      containers:
      - name: prospectus-backend-retrieve
        image: warpwing/hoyastest:latest
        ports:
        - containerPort: 5000
