apiVersion: apps/v1
kind: Deployment
metadata:
  name: prospectus-frontend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: prospectus-frontend
  template:
    metadata:
      labels:
        app: prospectus-frontend
    spec:
      containers:
      - name: prospectus-frontend
        image: warpwing/hoyasfrontend:latest
        ports:
        - containerPort: 80
