apiVersion: v1
kind: Service
metadata:
  name: prospectus-frontend-lb
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
  selector:
    app: prospectus-frontend
