apiVersion: v1
kind: Service
metadata:
  name: prospectus-frontend-lb
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
  selector:
    app: prospectus-frontend
