apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: prospectus-frontend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prospectus-frontend
  minReplicas: 4
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
